title: Things I liked enough to journal about.
email: joao@diogoduarte.pt
description: >-
  Stuff I liked.
baseurl: ""
url: "https://blog.diogoduarte.pt"
github_username: joaodiogoduarte

# Garth theme (https://github.com/daviddarnes/garth)
remote_theme: daviddarnes/garth
logo: "/assets/logo.svg"
lang: en-GB
date_format: "%-d %B %Y"

author:
  name: "João Diogo Duarte"

permalink: pretty
excerpt_separator: <!-- more -->

paginate: 5
paginate_path: /page:num/

collections:
  posts:
    title: "Things I liked."
    output: true
    description: "Stuff I liked."

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
